spring:
  datasource:
    username: sa 
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
    packages:
      trust-all: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mail@mail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  from: mail@mail.com
  to: to-mail@mail.com
  
route:
  from: 
    active-mq: activemq:queue:message.q
  to: 
    db: jdbc:dataSourceH2